name: Dummy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [
          { name: "agent", context: "./backend/", dockerfile: "./backend/src/CloudCrafter.Agent.Console/Dockerfile" },
          { name: "backend", context: "./backend/", dockerfile: "./backend/src/CloudCrafter.Web/Dockerfile" },
          { name: "worker", context: "./backend/", dockerfile: "./backend/src/CloudCrafter.Worker.Console/Dockerfile" },
          { name: "frontend", context: "./frontend/", dockerfile: "./frontend/apps/web/Dockerfile" }
        ]
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Hello world ${{ matrix.image.name }} / ${{ matrix.platform }}
        run: echo "Hello, world!"
