name: Build and Push Docker Image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: "cloudcrafter-oss/"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

# Extract 
    - name: Extract metadata (tags, labels) for Docker - Agent
      id: meta-agent
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/cloudcrafter-agent
        tags: |
          type=semver,pattern={{version}}

    - name: Extract metadata (tags, labels) for Docker - Backend
      id: meta-backend
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/cloudcrafter-backend
        tags: |
          type=semver,pattern={{version}}

    - name: Extract metadata (tags, labels) for Docker - Frontend
      id: meta-frontend
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/cloudcrafter-frontend
        tags: |
          type=semver,pattern={{version}}
# Build
    - name: Build and push CloudCrafter Agent Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend/
        file: ./backend/src/CloudCrafter.Agent.Console/Dockerfile
        push: true
        tags: ${{ steps.meta-agent.outputs.tags }}
        labels: ${{ steps.meta-agent.outputs.labels }}

    - name: Build and push CloudCrafter Backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend/
        file: ./backend/src/CloudCrafter.Backend/Dockerfile
        push: true
        tags: ${{ steps.meta-backend.outputs.tags }}
        labels: ${{ steps.meta-backend.outputs.labels }}

    - name: Build and push CloudCrafter Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/
        file: ./frontend/Dockerfile
        push: true
        build-args: |
          CLOUDCRAFTER_AXIOS_BACKEND_BASEURL=http://dummy
        tags: ${{ steps.meta-frontend.outputs.tags }}
        labels: ${{ steps.meta-frontend.outputs.labels }}