name: Validate Website

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/apps/site/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/apps/site/**'

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: "cloudcrafter-oss"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t cloudcrafter-docs --no-cache -f frontend/apps/site/Dockerfile ./frontend/

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-workspace.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm run format-and-lint

  deploy:
    needs: [build, lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push CloudCrafter Worker Docker image
        uses: docker/build-push-action@v4
        with:
            context: ./frontend/
            file: ./frontend/apps/site/Dockerfile
            push: true
            platforms: linux/amd64,linux/arm64
            tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/cloudcrafter-site:latest

  notify:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Plane
        run: ${{ secrets.PLANE_NOTIFICATION_COMMAND }}


